# -*- mode: python -*-

Import("env")

env.Library('command_request',
            'command_request.cpp',
            LIBDEPS=[
                '$BUILD_DIR/mongo/network'
            ]
)

env.CppUnitTest('command_request_test',
                'command_request_test.cpp',
                LIBDEPS=[
                    'command_request'
                ]
)
